#!/usr/bin/env python3
"""Validate release checksum files against package roots.\n\nCoverage is discovered from dist/manifests/*-CHECKSUMS.txt, never hardcoded, so a new\nsuite is validated the moment it is packaged rather than whenever someone remembers to\nextend a list.\n\nChecksums are generated by tools/cut_release.py. Archives are deterministic, so a\nmismatch here means content genuinely changed, not that the zip was rebuilt.\nPre-v1.0.0 CHECKSUMS-*-v0.1.0.txt files at the repo root pin superseded releases and\nare intentionally not validated against current packages.\n"""
from __future__ import annotations

from dataclasses import dataclass
import json
from hashlib import sha256
from pathlib import Path
import re
import sys

REPO = Path(__file__).resolve().parents[1]
CHECKSUM_RE = re.compile(r"^([0-9a-fA-F]{64})\s+(.+)$")


@dataclass(frozen=True)
class ArtifactSet:
    name: str
    checksum_file: Path
    package_root: Path
    minimum_entries: int


def discover_artifact_sets() -> list[ArtifactSet]:
    """Enumerate every suite that has a generated checksum file.

    This was a hardcoded list of seven while dist/skills held twenty-one, so fourteen
    suites shipped with their checksums unverified, including every desk added after the
    list was written. A literal list does not fail when it falls behind; it silently
    validates less and still reports success, which is the worst behaviour a release gate
    can have.

    minimum_entries is derived from the checksum file itself rather than from a literal,
    so it cannot drift again. An empty checksum file is treated as a defect, not as a
    vacuously satisfied set.
    """
    sets: list[ArtifactSet] = []
    for cs in sorted((REPO / "dist" / "manifests").glob("*-CHECKSUMS.txt")):
        slug = cs.name[: -len("-CHECKSUMS.txt")]
        # Derive the expected count from the JSON manifest, NOT from the checksum file.
        # Deriving it from the file under test is self-referential: truncate the file and
        # the expectation shrinks with it, so the gate passes on a half-recorded suite.
        # Found by counterfactual, not by review.
        expected = 0
        for mf in sorted((REPO / "dist" / "manifests").glob(f"{slug}-v*.json")):
            try:
                expected = max(expected, int(json.loads(mf.read_text(encoding="utf-8"))
                                             .get("skill_count", 0)))
            except (ValueError, json.JSONDecodeError):
                continue
        if not expected:
            expected = sum(1 for _ in (REPO / "dist" / "packages" / slug).glob("*.zip"))
        sets.append(ArtifactSet(slug, cs, REPO / "dist" / "packages" / slug, expected))
    return sets


ARTIFACT_SETS = discover_artifact_sets()



def file_sha256(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def candidate_paths(package_root: Path, recorded_path: str) -> list[Path]:
    raw = recorded_path.strip().replace("\\", "/")
    path = Path(raw)
    candidates = []
    if path.is_absolute():
        candidates.append(path)
    else:
        candidates.append(REPO / path)
        candidates.append(package_root / path)
        candidates.append(package_root / path.name)
    seen: set[Path] = set()
    unique: list[Path] = []
    for candidate in candidates:
        normalized = candidate.resolve() if candidate.exists() else candidate
        if normalized not in seen:
            unique.append(candidate)
            seen.add(normalized)
    return unique


def validate_artifact_set(artifact_set: ArtifactSet) -> list[str]:
    errors: list[str] = []
    entries = 0
    print(f"Checking {artifact_set.name}")

    if not artifact_set.checksum_file.exists():
        return [f"missing checksum file: {artifact_set.checksum_file.relative_to(REPO)}"]
    if not artifact_set.package_root.exists():
        return [f"missing package root: {artifact_set.package_root.relative_to(REPO)}"]

    for line_no, line in enumerate(artifact_set.checksum_file.read_text(encoding="utf-8").splitlines(), start=1):
        match = CHECKSUM_RE.match(line.strip())
        if not match:
            continue
        entries += 1
        expected, recorded_path = match.groups()
        expected = expected.lower()
        resolved = next((p for p in candidate_paths(artifact_set.package_root, recorded_path) if p.exists()), None)
        if resolved is None:
            errors.append(f"{artifact_set.checksum_file.relative_to(REPO)}:{line_no}: missing artifact {recorded_path}")
            continue
        actual = file_sha256(resolved)
        if actual != expected:
            errors.append(
                f"{artifact_set.checksum_file.relative_to(REPO)}:{line_no}: hash mismatch for {recorded_path}; expected {expected}; actual {actual}"
            )

    # The forward check proves every recorded line resolves. It cannot see an archive that
    # was packaged and never recorded, which is how a truncated or stale checksum file
    # passes while shipping unverified content. Walk the package root too.
    recorded_names = {
        Path(m.group(2).strip().replace("\\", "/")).name
        for m in (CHECKSUM_RE.match(ln.strip())
                  for ln in artifact_set.checksum_file.read_text(encoding="utf-8").splitlines())
        if m
    }
    for archive in sorted(artifact_set.package_root.glob("*.zip")):
        if archive.name not in recorded_names:
            errors.append(
                f"{artifact_set.checksum_file.relative_to(REPO)}: packaged archive is not "
                f"recorded: {archive.relative_to(REPO).as_posix()}"
            )

    if entries < artifact_set.minimum_entries:
        errors.append(
            f"{artifact_set.checksum_file.relative_to(REPO)}: expected at least {artifact_set.minimum_entries} checksum entries; found {entries}"
        )

    if errors:
        print(f"FAIL: {artifact_set.name} ({len(errors)} issue(s))")
    else:
        print(f"OK: {artifact_set.name} ({entries} entries)")
    return errors


def main() -> int:
    errors: list[str] = []
    for artifact_set in ARTIFACT_SETS:
        errors.extend(validate_artifact_set(artifact_set))

    if errors:
        print("\nRelease artifact validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("\nRelease artifact validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
